import "./globals.css";
import Navbar from "./components/Navbar";
import { Outfit } from "next/font/google";
import Footer from "./components/Footer";
import CustomLayout from "./components/CustomLayout";



const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  );
}
